### ISSUE TITLE
cannot import crosscat.LocalEngine

### ISSUE THREAD

**Issue by santhoshnarayan** [probcomp/crosscat#120]
Has anyone else seen this issue?

import crosscat.LocalEngine as LE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/python2/lib/python2.7/site-packages/crosscat/LocalEngine.py", line 28, in <module>
    import crosscat.cython_code.State as State
  File "__init__.pxd", line 155, in init crosscat.cython_code.State (src/cython_code/State.cpp:17827)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

It appears to be a numpy versioning issue from a quick google search.. does anyone happen to have a shareable env with this package working?

**Comment by santhoshnarayan** [comment]
resolved - pandas was missing in my python2 virtualenv
