### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fonnesbeck** [probcomp/crosscat#82]
Based on the following install error from pip, it appears that crosscat is not Python 3 compatible:

```
$ pip install git+https://github.com/probcomp/crosscat.git
Collecting git+https://github.com/probcomp/crosscat.git
  Cloning https://github.com/probcomp/crosscat.git to /var/folders/7q/rgspm2s915d7nctflyjjgx5r0000gn/T/pip-gu18rboj-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/7q/rgspm2s915d7nctflyjjgx5r0000gn/T/pip-gu18rboj-build/setup.py", line 53, in <module>
        version = get_version()
      File "/var/folders/7q/rgspm2s915d7nctflyjjgx5r0000gn/T/pip-gu18rboj-build/setup.py", line 15, in get_version
        if version.endswith('+'):
    TypeError: endswith first arg must be bytes or a tuple of bytes, not str

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/7q/rgspm2s915d7nctflyjjgx5r0000gn/T/pip-gu18rboj-build
fonnescj on Christy.local in ~/Repositories/
```

Are there plans for compatibility?

**Comment by gregory-marton** [comment]
We had a push towards compatibility some time ago that did result in a compatible version, but incompatibilities may have crept in, because we never added an integration test to ensure that it remained compatible. If you can get it back to a compatible state, then I would very much welcome the pull request, and I will, in fact, set up that integration test this time.

The larger issue is whether bayeslite and bdbcontrib can also be compatible. We haven't evaluated the extent of the work that would take well enough to come up with a plan or a prioritization for that. But questions like this one do help us set priorities, so thanks for asking!
